name: "dlh_duty_plan_converter"

services:
    dlh_duty_plan_converter:
        container_name: "dlh_duty_plan_converter"
        image: "ghcr.io/9-fs/dlh_duty_plan_converter:latest"
        mem_limit: "1G"
        volumes:
            - "/path/to/dlh_duty_plan_converter/calendar/:/app/calendar/"
            - "/path/to/dlh_duty_plan_converter/config/:/app/config/"
            - "/path/to/dlh_duty_plan_converter/db/:/app/db/"
            - "/path/to/dlh_duty_plan_converter/log/:/app/log/"